# Generated by Django 3.0.2 on 2020-01-12 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=2200)),
                ('detail', models.CharField(blank=True, max_length=2200, null=True)),
                ('image', models.ImageField(upload_to='')),
                ('date_published', models.DateTimeField(auto_now_add=True, verbose_name='date published')),
                ('lang', models.CharField(choices=[('python', 'Python'), ('js', 'Javascript'), ('django', 'Django')], max_length=200)),
            ],
        ),
    ]
